### ISSUE TITLE
Course page- upper and lower case can be used for same course

### ISSUE THREAD

**Issue by hsm022** [sam2127/CS372-AssignmentOrganizer#107]
I added cs as course code and b as course name, it was added successfully. 
Then I added CS as course code and B as course name, it was also added successfully, This should not be allowed since course cs already exists in lower case.

**Comment by sam2127** [comment]
Thanks for bringing this to my attention, Harpinder. Actually, I have intentionally kept this condition to allow a user to edit an already added course.  

If we don't do this then they cannot edit the course name for an existing course i.e. they won't be able to change the course name from "b" to "B" if they wanted to capitalize the characters. 

For example, in the screenshot below, a user entered a course with the course code as "cs" and the course name as "b". Now assume that he wants to edit the same course and wants to capitalize the alphabets for both the course code ("CS") and the course name ("B"), they won't be able to do it. 

![image](https://user-images.githubusercontent.com/61511436/100489901-f4077580-30dc-11eb-9bd9-bff3d9f97671.png)
